### ISSUE TITLE
`struct` word is highlighted if it's part of name

### ISSUE THREAD

**Issue by alexesprit** [0x9ef/vscode-vlang#105]
Also, `interface`, `enum` were highlighted too, but it was before 9b211346ec37369468fc0997fa7a1ae8338d6576.

![image](https://user-images.githubusercontent.com/1119267/72206421-c1da2e80-349e-11ea-882b-1e7125a00c7d.png)

**Comment by 0x9ef** [comment]
Fixed in https://github.com/0x9ef/vscode-vlang/commit/3e8f67f2abcb8e9ad8903b523ba8fd0ad16b4f67

**Comment by alexesprit** [comment]
@0x9ef It's not fixed for cases when `struct` word is followed by something else.

![image](https://user-images.githubusercontent.com/1119267/72218950-b4ca4780-3551-11ea-8079-13666b669c15.png)

**Comment by danieldaeschle** [comment]
![image](https://user-images.githubusercontent.com/30751516/79486005-5f9d4680-8016-11ea-9cfd-9cd8ec2cdbaf.png)

**Comment by danieldaeschle** [comment]
@0x9ef please reopen it??

**Comment by 0x9ef** [comment]
@danieldaeschle fixed in https://github.com/0x9ef/vscode-vlang/commit/3b682a9e31ec72257e351510be77126474921834

**Comment by danieldaeschle** [comment]
Thanks
